"""Convert a MIDI file into a Sheet this player can perform.

Notes that start at (nearly) the same moment become a chord; the gap to the
next chord becomes the note length. Notes outside the 61-key range are folded
back by whole octaves, which is what people do by hand anyway.

Needs `mido`:  pip install mido
"""

from __future__ import annotations

from pathlib import Path

from . import keymap
from .sheet import Event, Sheet

# MIDI note 60 is middle C (C4). Our internal pitch index puts C4 at 48.
MIDI_OFFSET = 12


class MidiError(RuntimeError):
    pass


def _require_mido():
    try:
        import mido
    except ImportError as exc:  # pragma: no cover - depends on the environment
        raise MidiError(
            "Reading MIDI files needs the 'mido' package:\n    pip install mido"
        ) from exc
    return mido


def _fold_into_range(pitch: int) -> int | None:
    """Shift by octaves until the note fits on the 61-key piano."""
    while pitch < keymap.LOWEST_PITCH:
        pitch += 12
    while pitch > keymap.HIGHEST_PITCH:
        pitch -= 12
    return pitch if pitch in keymap.PITCH_TO_NOTE else None


def convert(
    path: str | Path,
    *,
    tempo: float = 150.0,
    unit: int = 16,
    quantize: float = 0.5,
    chord_window: float = 0.03,
    fold: bool = True,
    max_voices: int = 6,
) -> Sheet:
    """Read `path` and return a playable Sheet.

    tempo/unit set the grid the result is written on; `quantize` is the
    smallest note length in units (0.5 = half a sixteenth, i.e. a 32nd).
    `chord_window` is how far apart two notes can start and still count as
    one chord, in seconds.
    """
    mido = _require_mido()
    path = Path(path)
    try:
        midi = mido.MidiFile(str(path))
    except Exception as exc:
        raise MidiError(f"could not read {path.name}: {exc}") from exc

    # Absolute start time, in seconds, of every note-on.
    onsets: list[tuple[float, int]] = []
    now = 0.0
    for message in midi:
        now += message.time
        if message.type == "note_on" and message.velocity > 0:
            onsets.append((now, message.note))

    if not onsets:
        raise MidiError(f"{path.name} contains no notes")

    onsets.sort(key=lambda item: item[0])

    # Group near-simultaneous onsets into chords.
    groups: list[tuple[float, list[int]]] = []
    for start, note in onsets:
        if groups and start - groups[-1][0] <= chord_window:
            groups[-1][1].append(note)
        else:
            groups.append((start, [note]))

    seconds_per_unit = (60.0 / tempo) * (4.0 / unit)
    sheet = Sheet(title=path.stem, tempo=tempo, unit=unit, hold=0.8)

    def snap(value: float) -> float:
        return max(quantize, round(value / quantize) * quantize)

    # A leading rest, so the piece does not start mid-beat.
    if groups[0][0] > seconds_per_unit:
        sheet.events.append(Event([], snap(groups[0][0] / seconds_per_unit), "midi"))

    skipped = 0
    for index, (start, notes) in enumerate(groups):
        if index + 1 < len(groups):
            span = groups[index + 1][0] - start
        else:
            span = seconds_per_unit * unit  # let the last chord ring for a bar
        length = snap(span / seconds_per_unit)

        names: list[str] = []
        for note in sorted(set(notes)):
            pitch = note - MIDI_OFFSET
            if pitch not in keymap.PITCH_TO_NOTE:
                if not fold:
                    skipped += 1
                    continue
                folded = _fold_into_range(pitch)
                if folded is None:
                    skipped += 1
                    continue
                pitch = folded
            names.append(keymap.PITCH_TO_NOTE[pitch])

        # Keep the outer voices when a chord is too thick to play cleanly.
        names = sorted(set(names), key=lambda n: keymap.NOTE_PITCH[n])
        if len(names) > max_voices:
            keep = max_voices // 2
            names = names[:keep] + names[-(max_voices - keep):]

        sheet.events.append(Event(names, length, "midi"))

    sheet.skipped_notes = skipped  # type: ignore[attr-defined]
    return sheet


def to_text(sheet: Sheet, per_line: int = 16) -> str:
    """Render a Sheet back into the project's text format, so it can be edited."""
    lines = [
        f"; {sheet.title} — sheet generated by vpiano, edit freely",
        f"@title {sheet.title}",
        f"@tempo {sheet.tempo:g}",
        f"@unit {sheet.unit}",
        f"@hold {sheet.hold:g}",
        "",
        ":midi",
    ]

    tokens: list[str] = []
    for event in sheet.events:
        body = "~" if event.is_rest else (
            event.notes[0] if len(event.notes) == 1 else "[" + " ".join(event.notes) + "]"
        )
        length = "" if event.units == 1 else f":{event.units:g}"
        tokens.append(body + length)

    for start in range(0, len(tokens), per_line):
        lines.append(" ".join(tokens[start:start + per_line]))

    return "\n".join(lines) + "\n"
